# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${output_dir}/checkpoints/
  filename: "e{epoch:03d}-s{step:06d}"
  save_last: null # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: -1 # save k best models (determined by above metric)
  auto_insert_metric_name: False # when True, the checkpoints filenames will contain the metric name
  save_weights_only: True # if True, then only the model’s weights will be saved
  every_n_train_steps: null # number of training steps between checkpoints
  every_n_epochs: 5 # number of epochs between checkpoints