# @package _global_
defaults:
  - override /data: supermotion3d/TEST_mm_hml3d
  - override /callbacks: null
  - _self_

task: test

# utilities in the entry file
# will not override previous setting if already set
ckpt_path: ???
ckpt_type: pl

seed: 42

model:
  pipeline:
    args:
      mm_num_repeats: 30

# Callbacks
callbacks:
  # o3d_mr_motion:
  #   _target_: hmr4d.utils.callbacks.o3d_vis_motion.MotionVisualizer
  #   name: o3d_motion_vis 
  #   time_postfix: True
  #   max_batches: 1000

  metric_generation:
    _target_: hmr4d.model.supermotion.callbacks.metric_generation.MetricMM
    endecoder_opt:
      _target_: hmr4d.model.supermotion.utils.motion3d_endecoder.Hmlvec263OriginalEnDecoder
      stats_module: hmr4d.network.evaluator.statistics
      stats_name: T2M_VEC
    is_export: True
    exp_name: ${exp_name}
    data_name: ${data_name}


# lightning utilities
pl_trainer:
  devices: 1
logger: null
