# This config's starting path should be "model/"
defaults:
  - /pipeline: null
  # choices are under common/optimizer & scheduler_cfg
  
_target_: hmr4d.model.supermotion.motion_prior_pl.MotionPriorPL

args:
  seed: ${seed}
  rng_type: seed_plus_idx # [const, random, seed_plus_idx]
