# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html
_target_: pytorch_lightning.callbacks.ModelCheckpoint
dirpath: ${output_dir}/checkpoints/
filename: "e{epoch:04d}-s{step:06d}"
save_top_k: 1 # save k best models (determined by above metric)
every_n_epochs: 1 # number of epochs between checkpoints
save_weights_only: False # if True, then only the model’s weights will be saved

save_last: True # additionally always save an exact copy of the last checkpoint to a file last.ckpt
auto_insert_metric_name: False # when True, the checkpoints filenames will contain the metric name
every_n_train_steps: null # number of training steps between checkpoints
