_target_: hmr4d.network.supermotion.ditlikev2.Network
# input
njoints: 1
nfeats: 135
text_dim: 512
imgseq_dim: 1027 # 512 for clip, 1024 for hmr, 1027 for hmr+bbx
# intermediate
latent_dim: 512 # cond-dim and net-dim
ff_size: 1024
num_layers: 8
num_heads: 4
# training
dropout: 0.1
