_target_: hmr4d.network.supermotion.ditlike.Network
# input
njoints: 22
nfeats: 2
text_dim: 512
imgseq_dim: 1024 # 512 for clip, 1024 for hmr
cam_dim: 4
# intermediate
latent_dim: 512 # cond-dim and net-dim
ff_size: 1024
num_layers: 8
num_heads: 4
# training
dropout: 0.1
