_target_: hmr4d.model.mas.utils.motion2d_endecoder.EuclideanEnDecoder
stats_module: hmr4d.network.mas.statistics
stats_name:  IDEA400_REPROJ_NR   #HML3D_PERS_NR #IDEA400_NR
J: 22 # SMPL22 + 1 next root
C: 2 