_target_: hmr4d.network.gmd.gmd_traj_net.GmdTrajNet

args_clip:
  # clip_pretrained_path: inputs/checkpoints/huggingface/clip-vit-large-patch14
  clip_target: CLIPTextModelWithProjection
  clip_pretrained_path: inputs/checkpoints/huggingface/clip-vit-base-patch32
  uncond_strategy: "zero_latent"

args_unet:
  input_dim: 4
  latent_dim: 512 # cond-dim and net-dim
  arch: unet
  dim_mults: [0.125, 0.25, 0.5]
  attention: False
  adagn: True
  zero: True
  version: "GMD_traj_release" # important

args:
  scheduler_type: "ddim"              # choices: ddim | ddpm
  num_inference_steps: 50
  num_visualize: 50
  scheduler_opt:
    beta_schedule: squaredcos_cap_v2  # cosine instead of linear
    prediction_type: epsilon
    clip_sample_range: 6.0            # in normalized space
    timestep_spacing: "linspace"

  guidance_scale: 2.5                 # CFG scale
  classifier_guidance:
    method: null
    t_start: 999
    t_end: 20
    cg_gmd_x0_v1:  # guided motion diffusion
      scale: 100.
      traj_as_rkpt: False  # use traj to guide the reconstruction instead of the given keypoints
    cg_gmd_x0_v2:  # guided motion diffusion + reweight trick
      scale: 100.
      reweight_x0: True
      traj_as_rkpt: False
  inpaint:
    t_start: 999
    t_end: 500

args_freeze:
  clip_trainable: null
  clip_proj_trainable: null
  unet_trainable: null
