# @package _global_

exp_name: debug

data:
  loader_opts:
    train:
      batch_size: 2
      num_workers: 0
    val_loader: 
      batch_size: 2
      num_workers: 0

pl_trainer:
  limit_train_batches: 6
  limit_val_batches: 0
  enable_checkpointing: False

callbacks:
  model_checkpoint: null
